### ISSUE TITLE
1.19.2 - Recipe for Wrench is broken

### ISSUE THREAD

**Issue by blob1807** [Rabbitminers/Extended-Cogwheels-Fabric#1]
## Bug
Recipe for Wrench is broken and now only includes one of any cog. However it can't be crafted in a bench nor Mechanical Crafter. Even with [polymorph](https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric) installed.
Additionally the Mechanical Crafter recipe crashes the game when viewed in REI.

### Crash Report
[Full crash Report](https://github.com/Rabbitminers/Extended-Cogwheels-Fabric/files/10784246/crash-2023-02-20_22.00.05-client.txt)

## Versions
MC - 1.19.2
Fabric - 0.14.14
Create - 0.5.0i-961
Extended Cogwheels - 0.5.0g-1.0.0

## Mods
[Full list of mods](https://gist.github.com/blob1807/064463c7078d002850b41f0b20731ee9)

**Comment by Gilberry** [comment]
I have created a pull request to fix the wrench recipe.

**Comment by Rabbitminers** [comment]
Patched in multiloader beta
